#!/bin/sh

# cd ${HOME}
# 设置语言环境为中文

export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:en_US

## Wayland 支持
# QT 优先使用 wayland，不可使用使，使用 xcb
export QT_QPA_PLATFORM="wayland;xcb"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
# Clutter 工具包
export CLUTTER_BACKEND=wayland

# Wayland 上运行 SDL 应用，一些游戏使用wayland
export SDL_VIDEODRIVER=wayland
# GTK后端为 wayland和x11，GTK 默认就是优先wayland
export GDK_BACKEND=wayland
# winit 默认使用 Wayland 后端，取消注释下行切换到 Xwayland
# WINIT_UNIX_BACKEND=x11

# 解决java程序启动黑屏错误
export _JAVA_AWT_WM_NONEREPARENTING=1

# 解决QT程序缩放问题
export QT_AUTO_SCREEN_SCALE_FACTOR=1
# 使用 qt5ct/qt6ct 软件配置 QT 程序外观
export QT_QPA_PLATFORMTHEME="qt5ct;qt6ct"

# Firefox
export MOZ_ENABLE_WAYLAND=1

# 配置 vulkan renderer
export WLR_RENDERER="vulkan"
# openglrenderer
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_CURRENT_DESKTOP=Hyprland
